'''Słownik zawiera produkt którego nie można jeść w ciąży:uzasadnienie'''

niejescwciazy_uzasadnienie = {
    "sushi": "Surowe ryby mogą zawierać pasożyty i bakterie, które mogą powodować infekcje szkodliwe dla matki i płodu.",
    "surowe jajka": "Surowe jajka mogą być zakażone salmonellą, co może prowadzić do zatrucia pokarmowego.",
    "surowe mieso": "Surowe mięso może zawierać bakterie takie jak E. coli i Salmonella, które mogą powodować poważne infekcje.",
    "surowe ryby": "Surowe ryby mogą zawierać pasożyty i bakterie, które mogą powodować infekcje szkodliwe dla matki i płodu.",
    "surowe owoce morza": "Surowe owoce morza mogą zawierać bakterie i wirusy, które mogą powodować zatrucia pokarmowe.",
    "niepasteryzowane mleko": "Niepasteryzowane mleko może zawierać bakterie takie jak Listeria, które mogą prowadzić do poważnych infekcji.",
    "niepasteryzowane sery": "Niepasteryzowane sery mogą zawierać bakterie takie jak Listeria, które mogą prowadzić do poważnych infekcji.",
    "niesprawdzone mieso": "Niesprawdzone mięso może zawierać bakterie i pasożyty, które mogą powodować infekcje.",
    "niesprawdzone ryby": "Niesprawdzone ryby mogą zawierać toksyny i pasożyty, które mogą być szkodliwe dla zdrowia.",
    "niesprawdzone owoce morza": "Niesprawdzone owoce morza mogą zawierać toksyny i pasożyty, które mogą być szkodliwe dla zdrowia.",
    "nieumyte owoce": "Nieumyte owoce mogą być skażone pestycydami i bakteriami, które mogą prowadzić do infekcji.",
    "nieumyte warzywa": "Nieumyte warzywa mogą być skażone pestycydami i bakteriami, które mogą prowadzić do infekcji.",
    "niesprawdzone grzyby": "Niesprawdzone grzyby mogą być toksyczne i zawierać substancje szkodliwe dla zdrowia.",
    "alkohol": "Spożycie alkoholu w ciąży może prowadzić do zespołu alkoholowego płodu, który powoduje poważne wady rozwojowe.",
    "kofeina (duża ilość: kawa, herbata, cola, czekolada)": "Nadmierne spożycie kofeiny może prowadzić do niskiej masy urodzeniowej dziecka oraz przedwczesnego porodu.",
    "niepasteryzowane produkty mleczne": "Niepasteryzowane produkty mleczne mogą zawierać bakterie takie jak Listeria, które mogą prowadzić do poważnych infekcji.",
    "żeń-szeń": "Żeń-szeń może wpływać na hormony i prowadzić do problemów z ciążą.",
    "kora kruszyny": "Kora kruszyny jest silnym środkiem przeczyszczającym i może prowadzić do skurczów macicy.",
    "senes": "Senes jest silnym środkiem przeczyszczającym i może prowadzić do skurczów macicy.",
    "tatar": "Surowe mięso może zawierać bakterie takie jak E. coli i Salmonella, które mogą powodować poważne infekcje.",
    "niewłaściwie przechowywane produkty": "Niewłaściwe przechowywanie może prowadzić do rozwoju bakterii i pleśni, które mogą być szkodliwe.",
    "tuńczyk (duża ilość)": "Tuńczyk może zawierać wysokie poziomy rtęci, która może wpływać na rozwój mózgu płodu.",
    "papaja": "Niedojrzała papaja zawiera enzym papainę, która może wywoływać skurcze macicy.",
    "ananas (duża ilość)": "Ananas zawiera bromelainę, która w dużych ilościach może prowadzić do skurczów macicy.",
    "hibiskus": "Hibiskus może wpływać na hormony i prowadzić do problemów z ciążą.",
    "ziele dziurawca": "Ziele dziurawca może wpływać na hormony i metabolizm leków, co może być niebezpieczne w ciąży.",
    "dziczyzna": "Dziczyzna może zawierać bakterie i pasożyty, które mogą być szkodliwe dla zdrowia.",
}

